server:
  port: 8080
fdfs:
  so-timeout: 60000
  connect-timeout: 60000
  thumb-image:
    width: 150
    height: 150
  tracker-list:
    #TrackerList参数,支持多个
    - 10.0.4.17:22122
  web-server-url: http://110.42.251.23:8888/